webtalk_init -webtalk_dir /home/tommy/src/tomarus/midirouter/midirouter.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-12-24 14:16:28" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "nbo7bjf5tvso2dqhun4pl862d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 9.11 (stretch)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3200.573 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.812 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1577191925000" -context "sdk\\\\bsp/1577191925000"
webtalk_add_data -client sdk -key hwid -value "1577184036000" -context "sdk\\\\bsp/1577191925000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1577191925000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1577191925000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1577191925000"
webtalk_add_data -client sdk -key uid -value "1577191926000" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key hwid -value "1577184036000" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key bspid -value "1577191925000" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key projSize -value "88.37109375" -context "sdk\\\\application/1577191926000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1577193388634"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1577193388634"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1577193388634"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1577193388634"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1577193388634"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1577193388634"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1577193388634"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1577193388634"
webtalk_transmit -clientid 3168674610 -regid "" -xml /home/tommy/src/tomarus/midirouter/midirouter.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/tommy/src/tomarus/midirouter/midirouter.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/tommy/src/tomarus/midirouter/midirouter.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
